server:
  port: 7076
spring:
  boot:
     admin:
       client:
          url: http://localhost:9999
  config: 
     import: optional:configserver:http://localhost:8080
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  application:
    name: JRTP701-BIService
eureka:
   client:
      service-url:
          default-zone: http://localhost:8761/eureka
management:
    endpoint:
       env:
         enabled: true
         show-values: always
       health:
          show-details: always
    endpoints:
        web: 
           exposure:
                include: '*'